const freeLeagues = [
  'England Premier League',
  'England FA Cup',
  'Germany Bundesliga I',
  'Italy Serie A',
  'Spain Primera Liga',
  'France Ligue 1',
  'UEFA Champions League',
  'UEFA Europa League',
  'Europe - World Cup Qualifying',
  'International Match',
  'France Cup',
  'England Championship',
  'Germany Bundesliga II',
  'France Ligue 2',
  'Italy Serie B',
  'Spain Segunda',
  'France National',
  'Netherlands Eredivisie',
  'Netherlands Cup',
  'Portugal Primeira Liga',
  'Portugal Segunda Liga',
  'Portugal Campeonato Nacional',
  'Brazil Serie A',
  'Brazil Campeonato Cearense',
  'Brazil Copa Verde',
  'Brazil Campeonato Gaucho',
  'England League 1',
  'England League 2',
  'Scotland Premiership',
  'Scotland Championship',
  'Turkey Super Lig',
  'Belgium First Division A',
  'Switzerland Challenge League',
  'Netherlands Eerste Divisie',
  'Austria Bunedsliga',
  'Switzerland Super League',
  'Poland Ekstraklasa',
  'Russia Division 1',
  'Argentina Copa de la Liga Profesional',
  'Argentina Nacional B',
  'Australia A-League',
  'Australia Brisbane Premier League',
  'Australia Queensland Premier League',
  'Australia Brisbane Capital League 1',
  'Australia NPL Queensland',
  'Japan J-League',
  'Japan J2-League',
  'Israel Premier League',
  'El Salvador Clausura',
  'Solomon Islands S League',
];

const premiumLeagues = [

];

module.exports = {
  freeLeagues,
  premiumLeagues,
};
