const freeLeagues = [
  'England Premier League',
  'Germany Bundesliga I',
  'Italy Serie A',
  'Spain Primera Liga',
  'France Ligue 1',
  'UEFA Champions League',
  'UEFA Europa League',
  'France Cup',
  'England Championship',
  'Germany Bundesliga II',
  'France Ligue 2',
  'Italy Serie B',
  'Spain Segunda',
  'France National',
  'Netherlands Eredivisie',
  'Netherlands Cup',
  'Portugal Primeira Liga',
  'Portugal Segunda Liga',
  'Portugal Campeonato Nacional',
  'Brazil Serie A',
  'Brazil Campeonato Cearense',
  'Brazil Copa Verde',
  'England League 1',
  'England League 2',
  'Scotland Premiership',
  'Scotland Championship',
  'Turkey Super Lig',
  'Belgium First Division A',
  'Switzerland Challenge League',
  'Netherlands Eerste Divisie',
  'Austria Bunedsliga',
  'Poland Ekstraklasa',
  'Australia A-League',
  'Australia Brisbane Premier League',
  'Australia Brisbane Capital League 1',
  'Australia NPL Queensland',
  'Japan J-League',
  'Japan J2-League',
  'Israel Premier League',
  'Solomon Islands S League',
];

const premiumLeagues = [

];

module.exports = {
  freeLeagues,
  premiumLeagues,
};
